export const NUTRIENT_MAP = [
  { attr_id: 301, name: "Calcium, Ca", unit: "mg", usda_tag: "CA" },
  {
    attr_id: 205,
    name: "Carbohydrate, by difference",
    unit: "g",
    usda_tag: "CHOCDF",
  },
  { attr_id: 601, name: "Cholesterol", unit: "mg", usda_tag: "CHOLE" },
  { attr_id: 208, name: "Energy", unit: "kcal", usda_tag: "ENERC_KCAL" },
  {
    attr_id: 606,
    name: "Fatty acids, total saturated",
    unit: "g",
    usda_tag: "FASAT",
  },
  { attr_id: 204, name: "Total lipid (fat)", unit: "g", usda_tag: "FAT" },
  {
    attr_id: 605,
    name: "Fatty acids, total trans",
    unit: "g",
    usda_tag: "FATRN",
  },
  { attr_id: 303, name: "Iron, Fe", unit: "mg", usda_tag: "FE" },
  { attr_id: 291, name: "Fiber, total dietary", unit: "g", usda_tag: "FIBTG" },
  { attr_id: 306, name: "Potassium, K", unit: "mg", usda_tag: "K" },
  { attr_id: 307, name: "Sodium, Na", unit: "mg", usda_tag: "NA" },
  { attr_id: 203, name: "Protein", unit: "g", usda_tag: "PROCNT" },
  { attr_id: 269, name: "Sugars, total", unit: "g", usda_tag: "SUGAR" },
  { attr_id: 539, name: "Sugars, added", unit: "g", usda_tag: "SUGAR_ADD" },
  { attr_id: 324, name: "Vitamin D", unit: "IU", usda_tag: "VITD" },
  { attr_id: 513, name: "Alanine", unit: "g", usda_tag: "ALA_G" },
  { attr_id: 221, name: "Alcohol, ethyl", unit: "g", usda_tag: "ALC" },
  { attr_id: 511, name: "Arginine", unit: "g", usda_tag: "ARG_G" },
  { attr_id: 207, name: "Ash", unit: "g", usda_tag: "ASH" },
  { attr_id: 514, name: "Aspartic acid", unit: "g", usda_tag: "ASP_G" },
  { attr_id: 454, name: "Betaine", unit: "mg", usda_tag: "BETN" },
  { attr_id: 262, name: "Caffeine", unit: "mg", usda_tag: "CAFFN" },
  { attr_id: 639, name: "Campesterol", unit: "mg", usda_tag: "CAMD5" },
  { attr_id: 322, name: "Carotene, alpha", unit: "Âµg", usda_tag: "CARTA" },
  { attr_id: 321, name: "Carotene, beta", unit: "Âµg", usda_tag: "CARTB" },
  {
    attr_id: 326,
    name: "Vitamin D3 (cholecalciferol)",
    unit: "Âµg",
    usda_tag: "CHOCAL",
  },
  { attr_id: 421, name: "Choline, total", unit: "mg", usda_tag: "CHOLN" },
  { attr_id: 334, name: "Cryptoxanthin, beta", unit: "Âµg", usda_tag: "CRYPX" },
  { attr_id: 312, name: "Copper, Cu", unit: "mg", usda_tag: "CU" },
  { attr_id: 507, name: "Cystine", unit: "g", usda_tag: "CYS_G" },
  { attr_id: 268, name: "Energy", unit: "kJ", usda_tag: "ENERC_KJ" },
  {
    attr_id: 325,
    name: "Vitamin D2 (ergocalciferol)",
    unit: "Âµg",
    usda_tag: "ERGCAL",
  },
  { attr_id: 610, name: "10:00", unit: "g", usda_tag: "F10D0" },
  { attr_id: 611, name: "12:00", unit: "g", usda_tag: "F12D0" },
  { attr_id: 696, name: "13:00", unit: "g", usda_tag: "F13D0" },
  { attr_id: 612, name: "14:00", unit: "g", usda_tag: "F14D0" },
  { attr_id: 625, name: "14:01", unit: "g", usda_tag: "F14D1" },
  { attr_id: 652, name: "15:00", unit: "g", usda_tag: "F15D0" },
  { attr_id: 697, name: "15:01", unit: "g", usda_tag: "F15D1" },
  { attr_id: 613, name: "16:00", unit: "g", usda_tag: "F16D0" },
  { attr_id: 626, name: "16:1 undifferentiated", unit: "g", usda_tag: "F16D1" },
  { attr_id: 673, name: "16:1 c", unit: "g", usda_tag: "F16D1C" },
  { attr_id: 662, name: "16:1 t", unit: "g", usda_tag: "F16D1T" },
  { attr_id: 653, name: "17:00", unit: "g", usda_tag: "F17D0" },
  { attr_id: 687, name: "17:01", unit: "g", usda_tag: "F17D1" },
  { attr_id: 614, name: "18:00", unit: "g", usda_tag: "F18D0" },
  { attr_id: 617, name: "18:1 undifferentiated", unit: "g", usda_tag: "F18D1" },
  { attr_id: 674, name: "18:1 c", unit: "g", usda_tag: "F18D1C" },
  { attr_id: 663, name: "18:1 t", unit: "g", usda_tag: "F18D1T" },
  {
    attr_id: 859,
    name: "18:1-11t (18:1t n-7)",
    unit: "g",
    usda_tag: "F18D1TN7",
  },
  { attr_id: 618, name: "18:2 undifferentiated", unit: "g", usda_tag: "F18D2" },
  { attr_id: 670, name: "18:2 CLAs", unit: "g", usda_tag: "F18D2CLA" },
  { attr_id: 675, name: "18:2 n-6 c,c", unit: "g", usda_tag: "F18D2CN6" },
  { attr_id: 669, name: "18:2 t,t", unit: "g", usda_tag: "F18D2TT" },
  { attr_id: 619, name: "18:3 undifferentiated", unit: "g", usda_tag: "F18D3" },
  {
    attr_id: 851,
    name: "18:3 n-3 c,c,c (ALA)",
    unit: "g",
    usda_tag: "F18D3CN3",
  },
  { attr_id: 685, name: "18:3 n-6 c,c,c", unit: "g", usda_tag: "F18D3CN6" },
  { attr_id: 627, name: "18:04", unit: "g", usda_tag: "F18D4" },
  { attr_id: 615, name: "20:00", unit: "g", usda_tag: "F20D0" },
  { attr_id: 628, name: "20:01", unit: "g", usda_tag: "F20D1" },
  { attr_id: 672, name: "20:2 n-6 c,c", unit: "g", usda_tag: "F20D2CN6" },
  { attr_id: 689, name: "20:3 undifferentiated", unit: "g", usda_tag: "F20D3" },
  { attr_id: 852, name: "20:3 n-3", unit: "g", usda_tag: "F20D3N3" },
  { attr_id: 853, name: "20:3 n-6", unit: "g", usda_tag: "F20D3N6" },
  { attr_id: 620, name: "20:4 undifferentiated", unit: "g", usda_tag: "F20D4" },
  { attr_id: 855, name: "20:4 n-6", unit: "g", usda_tag: "F20D4N6" },
  { attr_id: 629, name: "20:5 n-3 (EPA)", unit: "g", usda_tag: "F20D5" },
  { attr_id: 857, name: "21:05", unit: "g", usda_tag: "F21D5" },
  { attr_id: 624, name: "22:00", unit: "g", usda_tag: "F22D0" },
  { attr_id: 630, name: "22:1 undifferentiated", unit: "g", usda_tag: "F22D1" },
  { attr_id: 858, name: "22:04", unit: "g", usda_tag: "F22D4" },
  { attr_id: 631, name: "22:5 n-3 (DPA)", unit: "g", usda_tag: "F22D5" },
  { attr_id: 621, name: "22:6 n-3 (DHA)", unit: "g", usda_tag: "F22D6" },
  { attr_id: 654, name: "24:00:00", unit: "g", usda_tag: "F24D0" },
  { attr_id: 671, name: "24:1 c", unit: "g", usda_tag: "F24D1C" },
  { attr_id: 607, name: "04:00", unit: "g", usda_tag: "F4D0" },
  { attr_id: 608, name: "06:00", unit: "g", usda_tag: "F6D0" },
  { attr_id: 609, name: "08:00", unit: "g", usda_tag: "F8D0" },
  {
    attr_id: 645,
    name: "Fatty acids, total monounsaturated",
    unit: "g",
    usda_tag: "FAMS",
  },
  {
    attr_id: 646,
    name: "Fatty acids, total polyunsaturated",
    unit: "g",
    usda_tag: "FAPU",
  },
  {
    attr_id: 693,
    name: "Fatty acids, total trans-monoenoic",
    unit: "g",
    usda_tag: "FATRNM",
  },
  {
    attr_id: 695,
    name: "Fatty acids, total trans-polyenoic",
    unit: "g",
    usda_tag: "FATRNP",
  },
  { attr_id: 313, name: "Fluoride, F", unit: "Âµg", usda_tag: "FLD" },
  { attr_id: 417, name: "Folate, total", unit: "Âµg", usda_tag: "FOL" },
  { attr_id: 431, name: "Folic acid", unit: "Âµg", usda_tag: "FOLAC" },
  { attr_id: 435, name: "Folate, DFE", unit: "Âµg", usda_tag: "FOLDFE" },
  { attr_id: 432, name: "Folate, food", unit: "Âµg", usda_tag: "FOLFD" },
  { attr_id: 212, name: "Fructose", unit: "g", usda_tag: "FRUS" },
  { attr_id: 287, name: "Galactose", unit: "g", usda_tag: "GALS" },
  { attr_id: 515, name: "Glutamic acid", unit: "g", usda_tag: "GLU_G" },
  { attr_id: 211, name: "Glucose (dextrose)", unit: "g", usda_tag: "GLUS" },
  { attr_id: 516, name: "Glycine", unit: "g", usda_tag: "GLY_G" },
  { attr_id: 512, name: "Histidine", unit: "g", usda_tag: "HISTN_G" },
  { attr_id: 521, name: "Hydroxyproline", unit: "g", usda_tag: "HYP" },
  { attr_id: 503, name: "Isoleucine", unit: "g", usda_tag: "ILE_G" },
  { attr_id: 213, name: "Lactose", unit: "g", usda_tag: "LACS" },
  { attr_id: 504, name: "Leucine", unit: "g", usda_tag: "LEU_G" },
  {
    attr_id: 338,
    name: "Lutein + zeaxanthin",
    unit: "Âµg",
    usda_tag: "LUT+ZEA",
  },
  { attr_id: 337, name: "Lycopene", unit: "Âµg", usda_tag: "LYCPN" },
  { attr_id: 505, name: "Lysine", unit: "g", usda_tag: "LYS_G" },
  { attr_id: 214, name: "Maltose", unit: "g", usda_tag: "MALS" },
  { attr_id: 506, name: "Methionine", unit: "g", usda_tag: "MET_G" },
  { attr_id: 304, name: "Magnesium, Mg", unit: "mg", usda_tag: "MG" },
  { attr_id: 428, name: "Menaquinone-4", unit: "Âµg", usda_tag: "MK4" },
  { attr_id: 315, name: "Manganese, Mn", unit: "mg", usda_tag: "MN" },
  { attr_id: 406, name: "Niacin", unit: "mg", usda_tag: "NIA" },
  { attr_id: 573, name: "Vitamin E, added", unit: "mg", usda_tag: "NULL" },
  { attr_id: 578, name: "Vitamin B-12, added", unit: "Âµg", usda_tag: "NULL" },
  { attr_id: 257, name: "Adjusted Protein", unit: "g", usda_tag: "NULL" },
  { attr_id: 664, name: "22:1 t", unit: "g", usda_tag: "NULL" },
  { attr_id: 676, name: "22:1 c", unit: "g", usda_tag: "NULL" },
  { attr_id: 856, name: "18:3i", unit: "g", usda_tag: "NULL" },
  {
    attr_id: 665,
    name: "18:2 t not further defined",
    unit: "g",
    usda_tag: "NULL",
  },
  { attr_id: 666, name: "18:2 i", unit: "g", usda_tag: "NULL" },
  { attr_id: 305, name: "Phosphorus, P", unit: "mg", usda_tag: "P" },
  { attr_id: 410, name: "Pantothenic acid", unit: "mg", usda_tag: "PANTAC" },
  { attr_id: 508, name: "Phenylalanine", unit: "g", usda_tag: "PHE_G" },
  { attr_id: 636, name: "Phytosterols", unit: "mg", usda_tag: "PHYSTR" },
  { attr_id: 517, name: "Proline", unit: "g", usda_tag: "PRO_G" },
  { attr_id: 319, name: "Retinol", unit: "Âµg", usda_tag: "RETOL" },
  { attr_id: 405, name: "Riboflavin", unit: "mg", usda_tag: "RIBF" },
  { attr_id: 317, name: "Selenium, Se", unit: "Âµg", usda_tag: "SE" },
  { attr_id: 518, name: "Serine", unit: "g", usda_tag: "SER_G" },
  { attr_id: 641, name: "Beta-sitosterol", unit: "mg", usda_tag: "SITSTR" },
  { attr_id: 209, name: "Starch", unit: "g", usda_tag: "STARCH" },
  { attr_id: 638, name: "Stigmasterol", unit: "mg", usda_tag: "STID7" },
  { attr_id: 210, name: "Sucrose", unit: "g", usda_tag: "SUCS" },
  { attr_id: 263, name: "Theobromine", unit: "mg", usda_tag: "THEBRN" },
  { attr_id: 404, name: "Thiamin", unit: "mg", usda_tag: "THIA" },
  { attr_id: 502, name: "Threonine", unit: "g", usda_tag: "THR_G" },
  {
    attr_id: 323,
    name: "Vitamin E (alpha-tocopherol)",
    unit: "mg",
    usda_tag: "TOCPHA",
  },
  { attr_id: 341, name: "Tocopherol, beta", unit: "mg", usda_tag: "TOCPHB" },
  { attr_id: 343, name: "Tocopherol, delta", unit: "mg", usda_tag: "TOCPHD" },
  { attr_id: 342, name: "Tocopherol, gamma", unit: "mg", usda_tag: "TOCPHG" },
  { attr_id: 501, name: "Tryptophan", unit: "g", usda_tag: "TRP_G" },
  { attr_id: 509, name: "Tyrosine", unit: "g", usda_tag: "TYR_G" },
  { attr_id: 510, name: "Valine", unit: "g", usda_tag: "VAL_G" },
  { attr_id: 318, name: "Vitamin A, IU", unit: "IU", usda_tag: "VITA_IU" },
  { attr_id: 320, name: "Vitamin A, RAE", unit: "Âµg", usda_tag: "VITA_RAE" },
  { attr_id: 418, name: "Vitamin B-12", unit: "Âµg", usda_tag: "VITB12" },
  { attr_id: 415, name: "Vitamin B-6", unit: "mg", usda_tag: "VITB6A" },
  {
    attr_id: 401,
    name: "Vitamin C, total ascorbic acid",
    unit: "mg",
    usda_tag: "VITC",
  },
  { attr_id: 328, name: "Vitamin D (D2 + D3)", unit: "Âµg", usda_tag: "VITD" },
  {
    attr_id: 430,
    name: "Vitamin K (phylloquinone)",
    unit: "Âµg",
    usda_tag: "VITK1",
  },
  {
    attr_id: 429,
    name: "Dihydrophylloquinone",
    unit: "Âµg",
    usda_tag: "VITK1D",
  },
  { attr_id: 255, name: "Water", unit: "g", usda_tag: "WATER" },
  { attr_id: 309, name: "Zinc, Zn", unit: "mg", usda_tag: "ZN" },
  { attr_id: 344, name: "Tocotrienol, alpha", unit: "mg", usda_tag: "TOCTRA" },
  { attr_id: 345, name: "Tocotrienol, beta", unit: "mg", usda_tag: "TOCTRB" },
  { attr_id: 346, name: "Tocotrienol, gamma", unit: "mg", usda_tag: "TOCTRG" },
  { attr_id: 347, name: "Tocotrienol,delta", unit: "mg", usda_tag: "TOCTRD" },
];
